import React, { useState } from 'react';
import { Sparkles, Lightbulb, RefreshCw, Layers, TrendingUp, CheckCircle } from 'lucide-react';
import { FilterState } from '../../types/analytics';

interface AiExecutiveInsightsProps {
  filters: FilterState;
  liveKPIs: any;
}

export const AiExecutiveInsights: React.FC<AiExecutiveInsightsProps> = ({
  filters,
  liveKPIs
}) => {
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [insightsOutput, setInsightsOutput] = useState<string | null>(null);

  const filterSummary = React.useMemo(() => {
    const parts: string[] = [];
    if (filters.city !== 'All') parts.push(`City: ${filters.city}`);
    if (filters.academicLevel !== 'All') parts.push(`Level: ${filters.academicLevel}`);
    if (filters.digitalCategory !== 'All') parts.push(`Usage: ${filters.digitalCategory}`);
    if (filters.platform !== 'All') parts.push(`Platform: ${filters.platform}`);
    if (parts.length === 0) return 'All 10,000 Students';
    return parts.join(' · ');
  }, [filters]);

  const handleGenerateInsights = async () => {
    setIsLoading(true);
    setInsightsOutput(null);

    try {
      const response = await fetch('/api/ai/insights', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          context: {
            activeFiltersDescription: filterSummary,
            liveKPIs: liveKPIs
          }
        })
      });

      if (!response.ok) throw new Error('Insights generation failed');

      const data = await response.json();
      setInsightsOutput(data.text);
    } catch (err: any) {
      setInsightsOutput(`Error: ${err?.message || 'Server error'}`);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="bg-white border border-slate-200 rounded-lg p-5 shadow-xs space-y-4">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-3 pb-3 border-b border-slate-100">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-lg bg-purple-600 text-white flex items-center justify-center">
            <Sparkles className="w-4 h-4" />
          </div>
          <div>
            <h2 className="text-sm font-bold text-slate-900">
              Executive Insights Engine
            </h2>
            <p className="text-xs text-slate-500">
              Automated institutional briefing generated by Gemini for the active student cohort
            </p>
          </div>
        </div>

        <button
          onClick={handleGenerateInsights}
          disabled={isLoading}
          className="flex items-center gap-1.5 px-3.5 py-1.5 bg-slate-900 hover:bg-slate-800 text-white rounded-md text-xs font-semibold shadow-xs transition-colors disabled:opacity-50"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${isLoading ? 'animate-spin' : ''}`} />
          <span>{isLoading ? 'Synthesizing Cohort Metrics...' : 'Generate Executive Insights'}</span>
        </button>
      </div>

      {/* Cohort Snapshot Banner */}
      <div className="p-3 bg-purple-50/50 border border-purple-100 rounded-md text-xs flex flex-wrap items-center justify-between gap-2">
        <div className="flex items-center gap-2 text-purple-900">
          <span className="font-bold">Active Cohort Context:</span>
          <span className="font-mono text-purple-800">{filterSummary}</span>
        </div>
        <div className="font-mono text-[11px] text-purple-700">
          Enrolled: <strong>{liveKPIs.count}</strong> | Mean GPA: <strong>{liveKPIs.avgGPA}</strong> | Screen: <strong>{liveKPIs.avgScreenTime}h</strong>
        </div>
      </div>

      {/* Loading state */}
      {isLoading && (
        <div className="p-8 text-center space-y-2 border border-dashed border-slate-200 rounded-lg bg-slate-50/50">
          <div className="inline-block animate-spin rounded-full h-6 w-6 border-2 border-slate-300 border-t-purple-600"></div>
          <p className="text-xs text-slate-600 font-medium font-mono">
            Evaluating multivariate correlations, sleep debt elasticity, and performance bands...
          </p>
        </div>
      )}

      {/* Insights Display */}
      {insightsOutput && (
        <div className="bg-slate-50 border border-slate-200 rounded-lg p-4 space-y-3">
          <div className="prose prose-xs max-w-none text-xs text-slate-800 space-y-2 whitespace-pre-wrap leading-relaxed font-sans">
            {insightsOutput}
          </div>
        </div>
      )}

      {!insightsOutput && !isLoading && (
        <div className="text-center py-6 text-slate-400 text-xs">
          Click <strong>"Generate Executive Insights"</strong> to evaluate the current filtered cohort and generate structured strategic findings.
        </div>
      )}
    </div>
  );
};
